# Generated by Django 3.2.7 on 2021-09-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_prc', models.IntegerField(verbose_name='商品庫存量')),
                ('price', models.IntegerField(verbose_name='商品價格')),
                ('shop_id', models.CharField(max_length=10, verbose_name='商品隸屬館別')),
                ('vip', models.BooleanField(verbose_name='商品購買權限')),
                ('product_id', models.IntegerField(verbose_name='商品ID編號')),
            ],
            options={
                'verbose_name': '產品表',
                'verbose_name_plural': '產品表',
                'db_table': 'Product',
            },
        ),
    ]
