# Generated by Django 3.2.7 on 2021-10-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock_prc',
            new_name='stock_pcs',
        ),
    ]
