# Generated by Django 3.2.7 on 2021-09-28 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers', models.CharField(max_length=20, verbose_name='顧客ID')),
                ('qty', models.IntegerField(verbose_name='購買數量')),
                ('price', models.IntegerField(verbose_name='商品單價')),
                ('shop_id', models.IntegerField(verbose_name='商品隸屬館別')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='商品ID')),
            ],
            options={
                'verbose_name': '訂單表',
                'verbose_name_plural': '訂單表',
                'db_table': 'Customer_Order',
            },
        ),
    ]
