# Generated by Django 3.2.7 on 2021-10-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_order',
            name='shop_id',
            field=models.CharField(default='', max_length=10, verbose_name='商品隸屬館別'),
        ),
    ]
